<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>AccountVault</AssemblyName>
    <RootNamespace>AccountVault</RootNamespace>
    <ApplicationIcon>Assets\AccountVault.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AccountVault.Core\AccountVault.Core.csproj" />
    <Resource Include="Assets\AccountVault.ico" />
    <Resource Include="Assets\AccountVault.png" />
  </ItemGroup>
</Project>
